# Used to install the DB
apiVersion: v1
kind: Secret
metadata:
  name: explorer-postgres
  namespace: chiado
type: Opaque
stringData:
  db: DB_NAME
  user: DB_USER
  host: DB_HOST
  port: DB_PORT # "5432"
  pgpassword: USER_PASSWORD

---
apiVersion: v1
kind: Secret
metadata:
  name: explorer
  namespace: chiado
type: Opaque
stringData:
  # Google credentials, generate credentials on Google Compute Engine
  credentials.json: |
    {}
  explorer.config.yml: |
    # Alternatively, you can use environment variables:
    # https://github.com/gobitfly/eth2-beaconchain-explorer/blob/master/types/config.go#L8
    # Database credentials
    writerDatabase:
      user: "DB_USER"
      name: "DB_NAME"
      host: "DB_HOST"
      port: "DB_PORT"
      password: "DB_PASSWORD"
    readerDatabase:
      user: "DB_USER"
      name: "DB_NAME"
      host: "DB_HOST"
      port: "DB_PORT"
      password: "DB_PASSWORD"
    tieredCacheProvider: "redis" # you can choose between redis and bigtable
    redisCacheEndpoint: "0.0.0.0:6379"
    bigtable:
      project: NAME_OF_THE_BIGTABLE_PROJECT
      instance: NAME_OF_THE_INSTANCE

    # Chain network configuration (example will work for the prysm testnet)
    chain:
      network: "chiado"
      slotsPerEpoch: 16
      secondsPerSlot: 5
      genesisTimestamp: 1665396000
      mainnet: false # hide mainnet staking pool etc. info
      minGenesisActiveValidatorCount: 6000
      phase0path: "/gbc/config/config.yml"
      altairPath: "/gbc/config/config.yml"
      altairForkEpoch: 90
      configPath: "/gbc/config/config.yml"

    # Note: It is possible to run either the frontend or the indexer or both at the same time
    # Frontend config
    frontend:
      enabled: true # Enable or disable to web frontend
      imprint: "/gbc/config/imprint.html"
      siteName: "Chiado Beacon Chain Explorer"
      siteSubtitle: "🚇 Chiado Beacon Chain Explorer 🚇"
      siteDomain: 'beacon.chiadochain.net'
      csrfAuthKey: 'GENERATE_A_CSRF_AUTH_KEY'
      csrfInsecure: true
      jwtSigningSecret: "GENERATE_A_JWT_SIGNING_SECRET"
      jwtIssuer: "beacon.chiadochain.net"
      jwtValidityInMinutes: 30
      server:
        host: "0.0.0.0" # Address to listen on
        port: "3333" # Port to listen on
      writerDatabase:
        user: "DB_USER"
        name: "DB_NAME"
        host: "DB_HOST"
        port: "DB_PORT"
        password: "DB_PASSWORD"
      readerDatabase:
        user: "DB_USER"
        name: "DB_NAME"
        host: "DB_HOST"
        port: "DB_PORT"
        password: "DB_PASSWORD"
      eth1ExplorerBase: 'https://blockscout.chiadochain.net'
      eth1Currency: 'mGNO'
      eth1CurrencyName: 'mGNO'
      eth1CurrencyFormatDecimals: 5
      eth1Label: "CC"
      eth2Label: "CBC"

    # Indexer config
    indexer:
      enabled: false # Enable or disable the indexing service
      fullIndexOnStartup: false # Perform a one time full db index on startup - set true the first time only
      indexMissingEpochsOnStartup: false # Check for missing epochs and export them after startup
      ## You can also opt for a one time export:
      # onetimeexport:
      #   enabled: true
      #   startEpoch: 1000
      #   endEpoch: 23716
      node:
        host: 'https://rpc-gbc.chiadochain.net'
        port: "5052" # port of the backend node
        type: "lighthouse" # can be either prysm or lighthouse
        pageSize: 250 # the amount of entries to fetch per paged rpc call
      eth1Endpoint: 'https://rpc.chiadochain.net
      eth1DepositContractAddress: '0xb97036A26259B7147018913bD58a774cf91acf25'
      eth1DepositContractFirstBlock: 155399
    eth1ErigonEndpoint: 'https://rpc.chiadochain.net'
    eth1GethEndpoint: 'https://rpc.chiadochain.net'
